### ISSUE TITLE
ask high-frequency-factors-data

### ISSUE THREAD

**Issue by wencyxu** [jeremy-feng/high-frequency-factors#1]
Hello , is the processed data in the code available? I wanna  reproduce the code you provided.Thank you very much!

**Comment by jeremy-feng** [comment]
Hi, thank you for your interest. I didn't include the `/data` folder in the commit because the files were a bit large.

Please refer to [high-frequency-factors.zip](https://github.com/jeremy-feng/high-frequency-factors/files/12879781/high-frequency-factors.zip). It contains the complete project files.

**Comment by wencyxu** [comment]
> Hi, thank you for your interest. I didn't include the `/data` folder in the commit because the files were a bit large.
> 
> Please refer to [high-frequency-factors.zip](https://github.com/jeremy-feng/high-frequency-factors/files/12879781/high-frequency-factors.zip). It contains the complete project files.

thank you~
